services:
  readablock_server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: server
    command: >
      sh -c "python manage.py migrate --noinput &&
      gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    working_dir: /app
    volumes:
      - ./server:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - DEEPL_API_KEY=${DEEPL_API_KEY}
      - GOOGLE_TTS_API_KEY=${GOOGLE_TTS_API_KEY}
      - STORAGE_ACCESS_KEY_ID=${STORAGE_ACCESS_KEY_ID}
      - STORAGE_SECRET_ACCESS_KEY=${STORAGE_SECRET_ACCESS_KEY}
      - STORAGE_BUCKET_NAME=${STORAGE_BUCKET_NAME}
      - STORAGE_S3_ENDPOINT_URL=${STORAGE_S3_ENDPOINT_URL}
      - STORAGE_S3_REGION_NAME=${STORAGE_S3_REGION_NAME}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
    depends_on:
      - redis
    networks:
      - default
      - dokploy-network
    restart: unless-stopped

  readablock_client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: client
    ports:
      - "3001:3000"
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
  static_volume:
  media_volume:

networks:
  dokploy-network:
    external: true
