# Generated by Django 6.0 on 2026-09-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='daily_word_goal',
            field=models.IntegerField(choices=[(140, 'W140'), (550, 'W550'), (1370, 'W1370'), (2740, 'W2740')], null=True),
        ),
    ]
