# Generated by Django 6.0 on 2026-09-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usermeta_daily_word_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeta',
            name='daily_word_goal',
            field=models.PositiveIntegerField(choices=[(140, 'W140'), (550, 'W550'), (1370, 'W1370'), (2740, 'W2740')], null=True),
        ),
    ]
