LANGUAGES = [
    {"name": "Afrikaans", "deepl": "AF", "google_tts": "af-ZA", "marc": "afr"},
    {"name": "Albanian", "deepl": "SQ", "google_tts": None, "marc": "alb"},
    {"name": "Arabic", "deepl": "AR", "google_tts": "ar-XA", "marc": "ara"},
    {"name": "Aragonese", "deepl": "AN", "google_tts": None, "marc": "arg"},
    {"name": "Armenian", "deepl": "HY", "google_tts": None, "marc": "arm"},
    {"name": "Assamese", "deepl": "AS", "google_tts": None, "marc": "asm"},
    {"name": "Aymara", "deepl": "AY", "google_tts": None, "marc": "aym"},
    {"name": "Azerbaijani", "deepl": "AZ", "google_tts": None, "marc": "aze"},
    {"name": "Bashkir", "deepl": "BA", "google_tts": None, "marc": "bak"},
    {"name": "Basque", "deepl": "EU", "google_tts": "eu-ES", "marc": "baq"},
    {"name": "Belarusian", "deepl": "BE", "google_tts": None, "marc": "bel"},
    {"name": "Bengali", "deepl": "BN", "google_tts": "bn-IN", "marc": "ben"},
    {"name": "Bosnian", "deepl": "BS", "google_tts": "sr-RS", "marc": "bos"},
    {"name": "Breton", "deepl": "BR", "google_tts": None, "marc": "bre"},
    {"name": "Bulgarian", "deepl": "BG", "google_tts": "bg-BG", "marc": "bul"},
    {"name": "Burmese", "deepl": "MY", "google_tts": None, "marc": "bur"},
    {"name": "Cantonese", "deepl": "YUE", "google_tts": "yue-HK", "marc": "yue"},
    {"name": "Catalan", "deepl": "CA", "google_tts": "ca-ES", "marc": "cat"},
    {"name": "Chinese (simplified)", "deepl": "ZH", "google_tts": "cmn-CN", "marc": "chi"},
    {"name": "Chinese (simplified)", "deepl": "ZH-HANS", "google_tts": None, "marc": "chi"},
    {"name": "Chinese (traditional)", "deepl": "ZH-HANT", "google_tts": "cmn-TW", "marc": "chi"},
    {"name": "Croatian", "deepl": "HR", "google_tts": "sr-RS", "marc": "hrv"},
    {"name": "Czech", "deepl": "CS", "google_tts": "cs-CZ", "marc": "cze"},
    {"name": "Danish", "deepl": "DA", "google_tts": "da-DK", "marc": "dan"},
    {"name": "Dutch", "deepl": "NL", "google_tts": "nl-NL", "marc": "dut"},
    {"name": "Esperanto", "deepl": "EO", "google_tts": None, "marc": "epo"},
    {"name": "Estonian", "deepl": "ET", "google_tts": "et-EE", "marc": "est"},
    {"name": "Filipino", "deepl": "TL", "google_tts": "fil-PH", "marc": "tgl"},
    {"name": "Finnish", "deepl": "FI", "google_tts": "fi-FI", "marc": "fin"},
    {"name": "French", "deepl": "FR", "google_tts": "fr-FR", "marc": "fre"},
    {"name": "Galician", "deepl": "GL", "google_tts": None, "marc": "glg"},
    {"name": "Georgian", "deepl": "KA", "google_tts": None, "marc": "geo"},
    {"name": "German", "deepl": "DE", "google_tts": "de-DE", "marc": "ger"},
    {"name": "Greek", "deepl": "EL", "google_tts": "el-GR", "marc": "gre"},
    {"name": "Hebrew", "deepl": "HE", "google_tts": "he-IL", "marc": "heb"},
    {"name": "Hindi", "deepl": "HI", "google_tts": "hi-IN", "marc": "hin"},
    {"name": "Hungarian", "deepl": "HU", "google_tts": "hu-HU", "marc": "hun"},
    {"name": "Icelandic", "deepl": "IS", "google_tts": "is-IS", "marc": "ice"},
    {"name": "Indonesian", "deepl": "ID", "google_tts": "id-ID", "marc": "ind"},
    {"name": "Irish", "deepl": "GA", "google_tts": None, "marc": "gle"},
    {"name": "Italian", "deepl": "IT", "google_tts": "it-IT", "marc": "ita"},
    {"name": "Japanese", "deepl": "JA", "google_tts": "ja-JP", "marc": "jpn"},
    {"name": "Kazakh", "deepl": "KK", "google_tts": None, "marc": "kaz"},
    {"name": "Korean", "deepl": "KO", "google_tts": "ko-KR", "marc": "kor"},
    {"name": "Kyrgyz", "deepl": "KY", "google_tts": None, "marc": "kir"},
    {"name": "Latin", "deepl": "LA", "google_tts": None, "marc": "lat"},
    {"name": "Latvian", "deepl": "LV", "google_tts": "lv-LV", "marc": "lav"},
    {"name": "Lithuanian", "deepl": "LT", "google_tts": "lt-LT", "marc": "lit"},
    {"name": "Luxembourgish", "deepl": "LB", "google_tts": None, "marc": "ltz"},
    {"name": "Malay", "deepl": "MS", "google_tts": "ms-MY", "marc": "may"},
    {"name": "Malayalam", "deepl": "ML", "google_tts": "ml-IN", "marc": "mal"},
    {"name": "Maltese", "deepl": "MT", "google_tts": None, "marc": "mlt"},
    {"name": "Mongolian", "deepl": "MN", "google_tts": None, "marc": "mon"},
    {"name": "Nepali", "deepl": "NE", "google_tts": None, "marc": "nep"},
    {"name": "Norwegian", "deepl": "NB", "google_tts": "nb-NO", "marc": "nor"},
    {"name": "Persian (Farsi)", "deepl": "FA", "google_tts": None, "marc": "per"},
    {"name": "Polish", "deepl": "PL", "google_tts": "pl-PL", "marc": "pol"},
    {"name": "Portuguese (Brazilian)", "deepl": "PT-BR", "google_tts": "pt-BR", "marc": "por"},
    {"name": "Portuguese", "deepl": "PT-PT", "google_tts": "pt-PT", "marc": "por"},
    {"name": "Punjabi", "deepl": "PA", "google_tts": "pa-IN", "marc": "pan"},
    {"name": "Romanian", "deepl": "RO", "google_tts": "ro-RO", "marc": "rum"},
    {"name": "Russian", "deepl": "RU", "google_tts": "ru-RU", "marc": "rus"},
    {"name": "Serbian", "deepl": "SR", "google_tts": "sr-RS", "marc": "srp"},
    {"name": "Sesotho", "deepl": "ST", "google_tts": None, "marc": "sot"},
    {"name": "Sicilian", "deepl": "SCN", "google_tts": None, "marc": "scn"},
    {"name": "Slovak", "deepl": "SK", "google_tts": "sk-SK", "marc": "slo"},
    {"name": "Slovenian", "deepl": "SL", "google_tts": None, "marc": "slv"},
    {"name": "Spanish", "deepl": "ES", "google_tts": "es-ES", "marc": "spa"},
    {"name": "Swahili", "deepl": "SW", "google_tts": None, "marc": "swa"},
    {"name": "Swedish", "deepl": "SV", "google_tts": "sv-SE", "marc": "swe"},
    {"name": "Tamil", "deepl": "TA", "google_tts": "ta-IN", "marc": "tam"},
    {"name": "Tatar", "deepl": "TT", "google_tts": None, "marc": "tat"},
    {"name": "Telugu", "deepl": "TE", "google_tts": None, "marc": "tel"},
    {"name": "Thai", "deepl": "TH", "google_tts": "th-TH", "marc": "tha"},
    {"name": "Tsonga", "deepl": "TS", "google_tts": None, "marc": "tso"},
    {"name": "Tswana", "deepl": "TN", "google_tts": None, "marc": "tsn"},
    {"name": "Turkish", "deepl": "TR", "google_tts": "tr-TR", "marc": "tur"},
    {"name": "Turkmen", "deepl": "TK", "google_tts": None, "marc": "tuk"},
    {"name": "Ukrainian", "deepl": "UK", "google_tts": "uk-UA", "marc": "ukr"},
    {"name": "Urdu", "deepl": "UR", "google_tts": "ur-IN", "marc": "urd"},
    {"name": "Uzbek", "deepl": "UZ", "google_tts": None, "marc": "uzb"},
    {"name": "Vietnamese", "deepl": "VI", "google_tts": "vi-VN", "marc": "vie"},
    {"name": "Welsh", "deepl": "CY", "google_tts": None, "marc": "wel"},
    {"name": "Xhosa", "deepl": "XH", "google_tts": None, "marc": "xho"},
    {"name": "Yiddish", "deepl": "YI", "google_tts": None, "marc": "yid"},
    {"name": "Zulu", "deepl": "ZU", "google_tts": None, "marc": "zul"},
]

SUPPORTED_LANGUAGES = [lang["deepl"] for lang in LANGUAGES]

DEEPL_TO_GOOGLE = {lang["deepl"]: lang["google_tts"] for lang in LANGUAGES if lang["google_tts"]}
GOOGLE_TO_DEEPL = {lang["google_tts"]: lang["deepl"] for lang in LANGUAGES if lang["google_tts"]}
