LANGUAGES = [
    {"name": "Acehnese", "deepl": "ACE", "google": "", "marc": "ace"},
    {"name": "Afrikaans", "deepl": "AF", "google": "af-ZA", "marc": "afr"},
    {"name": "Albanian", "deepl": "SQ", "google": "sq-AL", "marc": "alb"},
    {"name": "Arabic", "deepl": "AR", "google": "ar-SA", "marc": "ara"},
    {"name": "Aragonese", "deepl": "AN", "google": "an-ES", "marc": "arg"},
    {"name": "Armenian", "deepl": "HY", "google": "hy-AM", "marc": "arm"},
    {"name": "Assamese", "deepl": "AS", "google": "as-IN", "marc": "asm"},
    {"name": "Aymara", "deepl": "AY", "google": "ay-BO", "marc": "aym"},
    {"name": "Azerbaijani", "deepl": "AZ", "google": "az-AZ", "marc": "aze"},
    {"name": "Bashkir", "deepl": "BA", "google": "ba-RU", "marc": "bak"},
    {"name": "Basque", "deepl": "EU", "google": "eu-ES", "marc": "baq"},
    {"name": "Belarusian", "deepl": "BE", "google": "be-BY", "marc": "bel"},
    {"name": "Bengali", "deepl": "BN", "google": "bn-IN", "marc": "ben"},
    {"name": "Bhojpuri", "deepl": "BHO", "google": "bho-IN", "marc": "bho"},
    {"name": "Bosnian", "deepl": "BS", "google": "bs-BA", "marc": "bos"},
    {"name": "Breton", "deepl": "BR", "google": "br-FR", "marc": "bre"},
    {"name": "Bulgarian", "deepl": "BG", "google": "bg-BG", "marc": "bul"},
    {"name": "Burmese", "deepl": "MY", "google": "my-MM", "marc": "bur"},
    {"name": "Cantonese", "deepl": "YUE", "google": "yue-HK", "marc": "yue"},
    {"name": "Catalan", "deepl": "CA", "google": "ca-ES", "marc": "cat"},
    {"name": "Cebuano", "deepl": "CEB", "google": "ceb-PH", "marc": "ceb"},
    {"name": "Chinese (simplified)", "deepl": "ZH", "google": "zh-CN", "marc": "chi"},
    {"name": "Chinese (simplified)", "deepl": "ZH-HANS", "google": "", "marc": "chi"},
    {"name": "Chinese (traditional)", "deepl": "ZH-HANT", "google": "zh-TW", "marc": "chi"},
    {"name": "Croatian", "deepl": "HR", "google": "hr-HR", "marc": "hrv"},
    {"name": "Czech", "deepl": "CS", "google": "cs-CZ", "marc": "cze"},
    {"name": "Danish", "deepl": "DA", "google": "da-DK", "marc": "dan"},
    {"name": "Dari", "deepl": "PRS", "google": "prs-AF", "marc": "prs"},
    {"name": "Dutch", "deepl": "NL", "google": "nl-NL", "marc": "dut"},
    {"name": "English (all variants)", "deepl": "EN", "google": "en-US", "marc": "eng"},
    {"name": "English (American)", "deepl": "EN-US", "google": "", "marc": "eng"},
    {"name": "English (British)", "deepl": "EN-GB", "google": "en-GB", "marc": "eng"},
    {"name": "Esperanto", "deepl": "EO", "google": "eo", "marc": "epo"},
    {"name": "Estonian", "deepl": "ET", "google": "et-EE", "marc": "est"},
    {"name": "Finnish", "deepl": "FI", "google": "fi-FI", "marc": "fin"},
    {"name": "French", "deepl": "FR", "google": "fr-FR", "marc": "fre"},
    {"name": "French (Canadian)", "deepl": "FR-CA", "google": "fr-CA", "marc": "fre"},
    {"name": "Galician", "deepl": "GL", "google": "gl-ES", "marc": "glg"},
    {"name": "Georgian", "deepl": "KA", "google": "ka-GE", "marc": "geo"},
    {"name": "German", "deepl": "DE", "google": "de-DE", "marc": "ger"},
    {"name": "German (Swiss)", "deepl": "DE-CH", "google": "de-CH", "marc": "ger"},
    {"name": "Greek", "deepl": "EL", "google": "el-GR", "marc": "gre"},
    {"name": "Guarani", "deepl": "GN", "google": "gn-PY", "marc": "grn"},
    {"name": "Gujarati", "deepl": "GU", "google": "gu-IN", "marc": "guj"},
    {"name": "Haitian Creole", "deepl": "HT", "google": "ht-HT", "marc": "hat"},
    {"name": "Hausa", "deepl": "HA", "google": "ha-NG", "marc": "hau"},
    {"name": "Hebrew", "deepl": "HE", "google": "he-IL", "marc": "heb"},
    {"name": "Hindi", "deepl": "HI", "google": "hi-IN", "marc": "hin"},
    {"name": "Hungarian", "deepl": "HU", "google": "hu-HU", "marc": "hun"},
    {"name": "Icelandic", "deepl": "IS", "google": "is-IS", "marc": "ice"},
    {"name": "Igbo", "deepl": "IG", "google": "ig-NG", "marc": "ibo"},
    {"name": "Indonesian", "deepl": "ID", "google": "id-ID", "marc": "ind"},
    {"name": "Irish", "deepl": "GA", "google": "ga-IE", "marc": "gle"},
    {"name": "Italian", "deepl": "IT", "google": "it-IT", "marc": "ita"},
    {"name": "Japanese", "deepl": "JA", "google": "ja-JP", "marc": "jpn"},
    {"name": "Javanese", "deepl": "JV", "google": "jv-ID", "marc": "jav"},
    {"name": "Kapampangan", "deepl": "PAM", "google": "pam-PH", "marc": "pam"},
    {"name": "Kazakh", "deepl": "KK", "google": "kk-KZ", "marc": "kaz"},
    {"name": "Konkani", "deepl": "GOM", "google": "gom", "marc": "gom"},
    {"name": "Korean", "deepl": "KO", "google": "ko-KR", "marc": "kor"},
    {"name": "Kurdish (Kurmanji)", "deepl": "KMR", "google": "kmr-TR", "marc": "kmr"},
    {"name": "Kurdish (Sorani)", "deepl": "CKB", "google": "ckb-IQ", "marc": "ckb"},
    {"name": "Kyrgyz", "deepl": "KY", "google": "ky-KG", "marc": "kir"},
    {"name": "Latin", "deepl": "LA", "google": "la", "marc": "lat"},
    {"name": "Latvian", "deepl": "LV", "google": "lv-LV", "marc": "lav"},
    {"name": "Lingala", "deepl": "LN", "google": "ln-CD", "marc": "lin"},
    {"name": "Lithuanian", "deepl": "LT", "google": "lt-LT", "marc": "lit"},
    {"name": "Lombard", "deepl": "LMO", "google": "", "marc": "lmo"},
    {"name": "Luxembourgish", "deepl": "LB", "google": "lb-LU", "marc": "ltz"},
    {"name": "Macedonian", "deepl": "MK", "google": "mk-MK", "marc": "mac"},
    {"name": "Maithili", "deepl": "MAI", "google": "mai-IN", "marc": "mai"},
    {"name": "Malagasy", "deepl": "MG", "google": "mg-MG", "marc": "mlg"},
    {"name": "Malay", "deepl": "MS", "google": "ms-MY", "marc": "may"},
    {"name": "Malayalam", "deepl": "ML", "google": "ml-IN", "marc": "mal"},
    {"name": "Maltese", "deepl": "MT", "google": "mt-MT", "marc": "mlt"},
    {"name": "Maori", "deepl": "MI", "google": "mi-NZ", "marc": "mao"},
    {"name": "Marathi", "deepl": "MR", "google": "mr-IN", "marc": "mar"},
    {"name": "Mongolian", "deepl": "MN", "google": "mn-MN", "marc": "mon"},
    {"name": "Nepali", "deepl": "NE", "google": "ne-NP", "marc": "nep"},
    {"name": "Norwegian Bokmål", "deepl": "NB", "google": "nb-NO", "marc": "nor"},
    {"name": "Occitan", "deepl": "OC", "google": "oc-FR", "marc": "oci"},
    {"name": "Oromo", "deepl": "OM", "google": "om-ET", "marc": "orm"},
    {"name": "Pangasinan", "deepl": "PAG", "google": "", "marc": "pag"},
    {"name": "Pashto", "deepl": "PS", "google": "ps-AF", "marc": "pus"},
    {"name": "Persian", "deepl": "FA", "google": "fa-IR", "marc": "per"},
    {"name": "Polish", "deepl": "PL", "google": "pl-PL", "marc": "pol"},
    {"name": "Portuguese (Brazilian)", "deepl": "PT-BR", "google": "pt-BR", "marc": "por"},
    {"name": "Portuguese (European)", "deepl": "PT-PT", "google": "pt-PT", "marc": "por"},
    {"name": "Portuguese (unspecified variant)", "deepl": "PT", "google": "pt-PT", "marc": "por"},
    {"name": "Punjabi", "deepl": "PA", "google": "pa-IN", "marc": "pan"},
    {"name": "Quechua", "deepl": "QU", "google": "qu-PE", "marc": "que"},
    {"name": "Romanian", "deepl": "RO", "google": "ro-RO", "marc": "rum"},
    {"name": "Russian", "deepl": "RU", "google": "ru-RU", "marc": "rus"},
    {"name": "Sanskrit", "deepl": "SA", "google": "sa-IN", "marc": "san"},
    {"name": "Serbian", "deepl": "SR", "google": "sr-RS", "marc": "srp"},
    {"name": "Sesotho", "deepl": "ST", "google": "st-LS", "marc": "sot"},
    {"name": "Sicilian", "deepl": "SCN", "google": "", "marc": "scn"},
    {"name": "Slovak", "deepl": "SK", "google": "sk-SK", "marc": "slo"},
    {"name": "Slovenian", "deepl": "SL", "google": "sl-SI", "marc": "slv"},
    {"name": "Spanish", "deepl": "ES", "google": "es-ES", "marc": "spa"},
    {"name": "Spanish (Latin American)", "deepl": "ES-419", "google": "es-419", "marc": "spa"},
    {"name": "Sundanese", "deepl": "SU", "google": "su-ID", "marc": "sun"},
    {"name": "Swahili", "deepl": "SW", "google": "sw-KE", "marc": "swa"},
    {"name": "Swedish", "deepl": "SV", "google": "sv-SE", "marc": "swe"},
    {"name": "Tagalog", "deepl": "TL", "google": "tl-PH", "marc": "tgl"},
    {"name": "Tajik", "deepl": "TG", "google": "tg-TJ", "marc": "tgk"},
    {"name": "Tamil", "deepl": "TA", "google": "ta-IN", "marc": "tam"},
    {"name": "Tatar", "deepl": "TT", "google": "tt-RU", "marc": "tat"},
    {"name": "Telugu", "deepl": "TE", "google": "te-IN", "marc": "tel"},
    {"name": "Thai", "deepl": "TH", "google": "th-TH", "marc": "tha"},
    {"name": "Tsonga", "deepl": "TS", "google": "ts-ZA", "marc": "tso"},
    {"name": "Tswana", "deepl": "TN", "google": "tn-BW", "marc": "tsn"},
    {"name": "Turkish", "deepl": "TR", "google": "tr-TR", "marc": "tur"},
    {"name": "Turkmen", "deepl": "TK", "google": "tk-TM", "marc": "tuk"},
    {"name": "Ukrainian", "deepl": "UK", "google": "uk-UA", "marc": "ukr"},
    {"name": "Urdu", "deepl": "UR", "google": "ur-PK", "marc": "urd"},
    {"name": "Uzbek", "deepl": "UZ", "google": "uz-UZ", "marc": "uzb"},
    {"name": "Vietnamese", "deepl": "VI", "google": "vi-VN", "marc": "vie"},
    {"name": "Welsh", "deepl": "CY", "google": "cy-GB", "marc": "wel"},
    {"name": "Wolof", "deepl": "WO", "google": "wo-SN", "marc": "wol"},
    {"name": "Xhosa", "deepl": "XH", "google": "xh-ZA", "marc": "xho"},
    {"name": "Yiddish", "deepl": "YI", "google": "yi", "marc": "yid"},
    {"name": "Zulu", "deepl": "ZU", "google": "zu-ZA", "marc": "zul"},
]

SUPPORTED_LANGUAGES = [lang["deepl"] for lang in LANGUAGES]

DEEPL_TO_GOOGLE = {lang["deepl"]: lang["google"] for lang in LANGUAGES if lang["google"]}
GOOGLE_TO_DEEPL = {lang["google"]: lang["deepl"] for lang in LANGUAGES if lang["google"]}
