# Generated by Django 6.0 on 2026-06-03 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):


    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('file', models.FileField(upload_to='books/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_books', to=settings.AUTH_USER_MODEL)),
                ('file_type', models.CharField(choices=[('epub', 'epub'), ('pdf', 'pdf'), ('txt', 'txt'), ('kepub', 'kepub')], default='epub', max_length=10)),
                ('language', models.CharField(choices=[('AF', 'AF'), ('SQ', 'SQ'), ('AR', 'AR'), ('AN', 'AN'), ('HY', 'HY'), ('AS', 'AS'), ('AY', 'AY'), ('AZ', 'AZ'), ('BA', 'BA'), ('EU', 'EU'), ('BE', 'BE'), ('BN', 'BN'), ('BS', 'BS'), ('BR', 'BR'), ('BG', 'BG'), ('MY', 'MY'), ('YUE', 'YUE'), ('CA', 'CA'), ('ZH', 'ZH'), ('ZH-HANS', 'ZH-HANS'), ('ZH-HANT', 'ZH-HANT'), ('HR', 'HR'), ('CS', 'CS'), ('DA', 'DA'), ('NL', 'NL'), ('EO', 'EO'), ('ET', 'ET'), ('TL', 'TL'), ('FI', 'FI'), ('FR', 'FR'), ('GL', 'GL'), ('KA', 'KA'), ('DE', 'DE'), ('EL', 'EL'), ('HE', 'HE'), ('HI', 'HI'), ('HU', 'HU'), ('IS', 'IS'), ('ID', 'ID'), ('GA', 'GA'), ('IT', 'IT'), ('JA', 'JA'), ('KK', 'KK'), ('KO', 'KO'), ('KY', 'KY'), ('LA', 'LA'), ('LV', 'LV'), ('LT', 'LT'), ('LB', 'LB'), ('MS', 'MS'), ('ML', 'ML'), ('MT', 'MT'), ('MN', 'MN'), ('NE', 'NE'), ('NB', 'NB'), ('FA', 'FA'), ('PL', 'PL'), ('PT-BR', 'PT-BR'), ('PT-PT', 'PT-PT'), ('PA', 'PA'), ('RO', 'RO'), ('RU', 'RU'), ('SR', 'SR'), ('ST', 'ST'), ('SCN', 'SCN'), ('SK', 'SK'), ('SL', 'SL'), ('ES', 'ES'), ('SW', 'SW'), ('SV', 'SV'), ('TA', 'TA'), ('TT', 'TT'), ('TE', 'TE'), ('TH', 'TH'), ('TS', 'TS'), ('TN', 'TN'), ('TR', 'TR'), ('TK', 'TK'), ('UK', 'UK'), ('UR', 'UR'), ('UZ', 'UZ'), ('VI', 'VI'), ('CY', 'CY'), ('XH', 'XH'), ('YI', 'YI'), ('ZU', 'ZU')], max_length=7)),
                ('reading_ease_score', models.FloatField(null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='BookProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_last_read', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
