# Generated by Django 6.0 on 2026-03-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bookunprocessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_type',
            field=models.CharField(choices=[('epub', 'epub'), ('pdf', 'pdf'), ('txt', 'txt'), ('kepub', 'kepub')], default='epub', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BookUnprocessed',
        ),
    ]
