# Generated by Django 6.0 on 2026-05-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_book_file_type_delete_bookunprocessed'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('it', 'it'), ('de', 'de')], default='it', max_length=5),
            preserve_default=False,
        ),
    ]
