# Generated by Django 6.0 on 2026-05-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reading_ease_score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('AF', 'AF'), ('SQ', 'SQ'), ('AR', 'AR'), ('AN', 'AN'), ('HY', 'HY'), ('AS', 'AS'), ('AY', 'AY'), ('AZ', 'AZ'), ('BA', 'BA'), ('EU', 'EU'), ('BE', 'BE'), ('BN', 'BN'), ('BS', 'BS'), ('BR', 'BR'), ('BG', 'BG'), ('MY', 'MY'), ('YUE', 'YUE'), ('CA', 'CA'), ('ZH', 'ZH'), ('ZH-HANS', 'ZH-HANS'), ('ZH-HANT', 'ZH-HANT'), ('HR', 'HR'), ('CS', 'CS'), ('DA', 'DA'), ('NL', 'NL'), ('EO', 'EO'), ('ET', 'ET'), ('TL', 'TL'), ('FI', 'FI'), ('FR', 'FR'), ('GL', 'GL'), ('KA', 'KA'), ('DE', 'DE'), ('EL', 'EL'), ('HE', 'HE'), ('HI', 'HI'), ('HU', 'HU'), ('IS', 'IS'), ('ID', 'ID'), ('GA', 'GA'), ('IT', 'IT'), ('JA', 'JA'), ('KK', 'KK'), ('KO', 'KO'), ('KY', 'KY'), ('LA', 'LA'), ('LV', 'LV'), ('LT', 'LT'), ('LB', 'LB'), ('MS', 'MS'), ('ML', 'ML'), ('MT', 'MT'), ('MN', 'MN'), ('NE', 'NE'), ('NB', 'NB'), ('FA', 'FA'), ('PL', 'PL'), ('PT-BR', 'PT-BR'), ('PT-PT', 'PT-PT'), ('PA', 'PA'), ('RO', 'RO'), ('RU', 'RU'), ('SR', 'SR'), ('ST', 'ST'), ('SCN', 'SCN'), ('SK', 'SK'), ('SL', 'SL'), ('ES', 'ES'), ('SW', 'SW'), ('SV', 'SV'), ('TA', 'TA'), ('TT', 'TT'), ('TE', 'TE'), ('TH', 'TH'), ('TS', 'TS'), ('TN', 'TN'), ('TR', 'TR'), ('TK', 'TK'), ('UK', 'UK'), ('UR', 'UR'), ('UZ', 'UZ'), ('VI', 'VI'), ('CY', 'CY'), ('XH', 'XH'), ('YI', 'YI'), ('ZU', 'ZU')], max_length=7),
        ),
    ]
