# Generated by Django 6.0 on 2026-05-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_book_reading_ease_score_alter_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
