# Generated by Django 6.0 on 2026-06-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial_squashed_0008_book_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bug', 'bug'), ('feature_request', 'feature_request'), ('general', 'general')], max_length=20)),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='file_type',
            field=models.CharField(choices=[('epub', 'epub'), ('pdf', 'pdf'), ('txt', 'txt'), ('kepub', 'kepub')], max_length=10),
        ),
    ]
