# Generated by Django 6.0 on 2026-08-02 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_sentence_options_bookupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookupload',
            name='user',
        ),
        migrations.AddField(
            model_name='bookupload',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.book'),
            preserve_default=False,
        ),
    ]
