# Generated by Django 6.0 on 2026-09-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_bookupload_user_bookupload_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sentence_count',
            field=models.IntegerField(default=0),
        ),
    ]
