# Generated by Django 6.0 on 2026-08-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_bookupload_user_bookupload_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='file',
        ),
        migrations.RemoveField(
            model_name='book',
            name='file_type',
        ),
        migrations.AddField(
            model_name='bookupload',
            name='file_type',
            field=models.CharField(choices=[('epub', 'epub'), ('pdf', 'pdf'), ('txt', 'txt'), ('kepub', 'kepub')], default='epub', max_length=10),
            preserve_default=False,
        ),
    ]
