# Generated by Django 6.0 on 2026-09-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_book_sentence_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sentence',
        ),
    ]
