# Generated by Django 6.0 on 2026-09-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_book_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
