# Generated by Django 6.0 on 2026-09-28 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_book_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('AF', 'AF'), ('SQ', 'SQ'), ('AR', 'AR'), ('AN', 'AN'), ('HY', 'HY'), ('AS', 'AS'), ('AY', 'AY'), ('AZ', 'AZ'), ('BA', 'BA'), ('EU', 'EU'), ('BE', 'BE'), ('BN', 'BN'), ('BS', 'BS'), ('BR', 'BR'), ('BG', 'BG'), ('MY', 'MY'), ('YUE', 'YUE'), ('CA', 'CA'), ('ZH', 'ZH'), ('ZH-HANS', 'ZH-HANS'), ('ZH-HANT', 'ZH-HANT'), ('HR', 'HR'), ('CS', 'CS'), ('DA', 'DA'), ('NL', 'NL'), ('EO', 'EO'), ('ET', 'ET'), ('TL', 'TL'), ('FI', 'FI'), ('FR', 'FR'), ('GL', 'GL'), ('KA', 'KA'), ('DE', 'DE'), ('EL', 'EL'), ('HE', 'HE'), ('HI', 'HI'), ('HU', 'HU'), ('IS', 'IS'), ('ID', 'ID'), ('GA', 'GA'), ('IT', 'IT'), ('JA', 'JA'), ('KK', 'KK'), ('KO', 'KO'), ('KY', 'KY'), ('LA', 'LA'), ('LV', 'LV'), ('LT', 'LT'), ('LB', 'LB'), ('MS', 'MS'), ('ML', 'ML'), ('MT', 'MT'), ('MN', 'MN'), ('NE', 'NE'), ('NB', 'NB'), ('FA', 'FA'), ('PL', 'PL'), ('PT-BR', 'PT-BR'), ('PT-PT', 'PT-PT'), ('PA', 'PA'), ('RO', 'RO'), ('RU', 'RU'), ('SR', 'SR'), ('ST', 'ST'), ('SCN', 'SCN'), ('SK', 'SK'), ('SL', 'SL'), ('ES', 'ES'), ('SW', 'SW'), ('SV', 'SV'), ('TA', 'TA'), ('TT', 'TT'), ('TE', 'TE'), ('TH', 'TH'), ('TS', 'TS'), ('TN', 'TN'), ('TR', 'TR'), ('TK', 'TK'), ('UK', 'UK'), ('UR', 'UR'), ('UZ', 'UZ'), ('VI', 'VI'), ('CY', 'CY'), ('XH', 'XH'), ('YI', 'YI'), ('ZU', 'ZU')], max_length=7)),
            ],
            options={
                'indexes': [models.Index(fields=['text'], name='app_word_text_392701_idx')],
                'constraints': [models.UniqueConstraint(fields=('text', 'language'), name='uniq_word_language')],
            },
        ),
        migrations.CreateModel(
            name='ReadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('word_count', models.PositiveSmallIntegerField(default=0)),
                ('word_goal', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uniq_user_date')],
            },
        ),
        migrations.CreateModel(
            name='WordRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_reads', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reads', to='app.word')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'word'], name='app_wordrea_user_id_2accbe_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'word', 'date'), name='uniq_user_word_date')],
            },
        ),
    ]
