# Generated by Django 6.0 on 2026-09-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_word_readinglog_wordread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglog',
            name='word_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='readinglog',
            name='word_goal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
