name: PR Agent

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
    types: [created]

jobs:
  pr_agent:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: PR Agent action step
        id: pragent
        uses: the-pr-agent/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI__KEY: ${{ secrets.ZAI_API_KEY }}
          OPENAI__API_BASE: "https://api.z.ai/api/paas/v4"
          PR_AGENT__GIT_PROVIDER: "github"
          CONFIG__GIT_PROVIDER: "github"
          OPENAI__MODEL: "glm-5.3-flash"
          PR_REVIEWER__EXTRA_INSTRUCTIONS: ""
          GITHUB_ACTION_CONFIG__AUTO_REVIEW: "true"
          GITHUB_ACTION_CONFIG__AUTO_DESCRIBE: "true"
          GITHUB_ACTION_CONFIG__AUTO_IMPROVE: "false"
